// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbuplvahovigrrqtyfay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNidXBsdmFob3ZpZ3JycXR5ZmF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMTI2MDIsImV4cCI6MjA1OTg4ODYwMn0.u7ntw7auskD7v3IXEnYzTIJxRwS84sllPGP9Wx13SQ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);